AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation Template for IAM

Parameters: 
  KendraIndexRole:
    Description: Kendra Index IAM Role Name 
    Type: String
    Default: Kendra-Index-Role

  KendraIndexPolicy:
    Description: Kendra Index IAM Policy Name 
    Type: String
    Default: Kendra-Index-Policy

  S3BucketKeyKendraIndexOps:
    Description: The name of the S3 Key which has the Lambda Code for creation of Index
    Type: String
    Default: kendra_custom_resource.zip
  
  KendraS3BucketName:
    AllowedPattern: ^[a-z0-9][a-z0-9-.]*$
    Description: The name of the S3 bucket which has the Kendra Docs for syncing
    Type: String
    Default: lex-kendra-data

  KendraIndexName:
    Description: The name of the Kendra Index
    Type: String
    Default: Lex-Kendra-Covid-Bot-Index-v5

  KendraIndexEdition:
    Description: Kendra Index Edition (DEVELOPER_EDITION or ENTERPRISE_EDITION)
    Type: String
    AllowedValues: 
      - DEVELOPER_EDITION
      - ENTERPRISE_EDITION
    Default: DEVELOPER_EDITION

  KendraDataSourceName:
    Description: The name of Data Source for the Kendra Index
    Type: String
    Default: lex-kendra-covid-bot-data-source

  KendraFAQName:
    Description: The name of FAQs for the Kendra Index
    Type: String
    Default: lex-kendra-covid-bot-faqs

  KendraFAQFileKey:
    Description: The file where FAQs are stored for the Kendra Index
    Type: String
    Default: COVID_FAQ_2.csv

  S3BucketName:
    AllowedPattern: ^[a-z0-9][a-z0-9-.]*$
    Description: The name of S3 Bucket in which Lambda code is present
    Type: String
    Default: lex-kendra-code

  S3BucketLambdaLayerKey:
    Description: The name of the S3 key which has the Layer libraries
    Type: String
    Default: layer.zip

Resources: 
  KendraIndexIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
            - kendra.amazonaws.com
            - s3.amazonaws.com
          Action:
          - sts:AssumeRole
      # Path: "/"
      RoleName: !Ref KendraIndexRole

  KendraIndexIAMPolicy:
    DependsOn:
    - KendraIndexIAMRole
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Ref KendraIndexPolicy
      Roles:
      - Ref: KendraIndexIAMRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - logs:*
          Resource:
          - arn:aws:logs:*:*:*
        - Effect: Allow
          Action:
          - s3:*
          Resource:
          - "*"
        - Effect: Allow
          Action:
          - kendra:*
          Resource:
          - "*"
        - Effect: Allow
          Action:
          - 'iam:GetRole'
          - 'iam:PassRole'
          Resource:
          - "*"
        - Effect: Allow
          Action:
          - lambda:*
          Resource:
          - "*"
        - Effect: Allow
          Action:
          - events:PutRule
          - events:DeleteRule
          - events:PutTargets
          - events:RemoveTargets
          Resource:
          - "*"
        - Effect: Allow
          Action:
          - cloudformation:DescribeStacks
          Resource:
          - "*"

  KendraOperationsFunctiontest3:
    DependsOn:
    - KendraIndexIAMPolicy
    Type: AWS::Lambda::Function
    Properties:
      Layers: [!Ref CrHelperLayer]
      FunctionName: KendraOperationsFunctiontest3
      Runtime: python3.6          
      Timeout: 900
      Role: !GetAtt KendraIndexIAMRole.Arn
      MemorySize: 256
      Handler: kendra_custom_resource.lambda_handler
      Code:
        S3Bucket: !Ref S3BucketName
        S3Key: !Ref S3BucketKeyKendraIndexOps
      Description: Lambda backed Custom Resource for Kendra Index Operations

  CrHelperLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.6
        - python3.7
      Content:
        S3Bucket: !Ref S3BucketName
        S3Key: !Ref S3BucketLambdaLayerKey
  
  KendraFunctiontest: 
    DependsOn:
    - KendraOperationsFunctiontest3
    Type: Custom::KendraFunctiontest
    Properties:
      ServiceToken: !GetAtt KendraOperationsFunctiontest3.Arn
      IndexRoleArn: !GetAtt KendraIndexIAMRole.Arn
      IndexName: !Ref KendraIndexName
      Edition: !Ref KendraIndexEdition
      DataSourceName: !Ref KendraDataSourceName
      KendraS3Bucket: !Ref KendraS3BucketName
      DataSourceRoleArn: !GetAtt KendraIndexIAMRole.Arn
      FAQName: !Ref KendraFAQName
      FAQRoleArn: !GetAtt KendraIndexIAMRole.Arn
      FAQFileKey: !Ref KendraFAQFileKey

Outputs:
  IAMRoleName:
    Description: Name of IAM Role
    Value: !Ref KendraIndexIAMRole
  
  IAMRoleARN:
    Description: ARN of IAM Role
    Value: !GetAtt KendraIndexIAMRole.Arn

  LambdaFunctionName:
    Description: Name of Lambda function used for Kendra Index Custom Resource Operations
    Value: !Ref KendraOperationsFunctiontest3
  
  LambdaFunctionARN:
    Description: ARN of Lambda Function used for Kendra Index Custom Resource Operations
    Value: !GetAtt KendraOperationsFunctiontest3.Arn

  KendraIndexID:
    Description: Index ID for the Kendra Index
    Value: !GetAtt KendraFunctiontest.KendraIndexId
    Export:
      Name: "KendraIndexID"