AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation Template # Description

Parameters: 
  LexBotRole:
    Description: Lex Bot IAM Role Name 
    Type: String
    Default: Lex-Bot-Role

  LexBotPolicy:
    Description: Lex Bot IAM Policy Name 
    Type: String
    Default: Lex-Bot-Policy
  
  LexBotS3FileKey:
    Description: The S3 file key where Lex Bot JSON is stored
    Type: String
    Default: covid_bot_connect_Export.json #Allowed Pattern

  S3BucketKeyLexBotOps:
    Description: The S3 file key of the Lambda Code for Lex Bot Operations
    Type: String
    Default: lex_bot_custom_resource.zip

  S3BucketName:
    AllowedPattern: ^[a-z0-9][a-z0-9-.]*$
    Description: The name of S3 Bucket in which Lambda code is present
    Type: String
    Default: lex-kendra-code

  S3BucketLambdaLayerKey:
    Description: The name of the S3 key which has the Layer libraries
    Type: String
    Default: layer.zip # Allowed Pattern

  LambdaFunctionARN:
    Description: ARN of Fallback intent Lambda
    Type: String #Allowed Pattern

  LexBotOpsFunctionName:
    Description: Name of Lambda function for lex bot setup
    Type: String
    

Resources: 
  LexBotIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lex.amazonaws.com
            - s3.amazonaws.com
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      #Path: "/"
      RoleName: !Ref LexBotRole

  LexBotIAMPolicy:
    DependsOn:
    - LexBotIAMRole
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Ref LexBotPolicy
      Roles:
      - Ref: LexBotIAMRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - logs:CreateLogGroup
          - logs:CreateLogStream
          - logs:PutLogEvents
          Resource:
          - arn:aws:logs:*:*:*
        - Effect: Allow
          Action:
          - s3:*
          Resource:
          - !Sub "arn:aws:s3:::${S3BucketName}"
          - !Sub "arn:aws:s3:*:*:accesspoint/*"
          - !Sub "arn:aws:s3:::${S3BucketName}/*"
        - Effect: Allow
          Action:
          - lex:*
          Resource:
          - "*"
        - Effect: Allow
          Action:
          - 'iam:GetRole'
          - 'iam:PassRole'
          Resource:
          - "*"
        - Effect: Allow
          Action:
          - lambda:AddPermission
          - lambda:RemovePermission
          Resource:
          - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${LexBotOpsFunctionName}"
        - Effect: Allow
          Action:
          - events:PutRule
          - events:DeleteRule
          - events:PutTargets
          - events:RemoveTargets
          Resource:
          - "*"

  CrHelperLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.6
        - python3.7
      Content:
        S3Bucket: !Ref S3BucketName
        S3Key: !Ref S3BucketLambdaLayerKey

  LexBotOpsFunctionTest:
    DependsOn:
    - LexBotIAMPolicy
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref LexBotOpsFunctionName
      Runtime: python3.6          
      Timeout: 600
      Role: !GetAtt LexBotIAMRole.Arn
      MemorySize: 256
      Handler: lex_bot_custom_resource.lambda_handler
      Layers: [!Ref CrHelperLayer]
      Code:
        S3Bucket: !Ref S3BucketName
        S3Key: !Ref S3BucketKeyLexBotOps
      Description: Lambda backed Custom-Resource for Lex bot operations

  LexBotOpsFunctionTrigger:
    DependsOn: 
      - LexBotOpsFunctionTest
    Type: Custom::LexBotOpsFunctionTrigger
    Properties:
      ServiceToken: !GetAtt LexBotOpsFunctionTest.Arn
      LexS3Bucket: !Ref S3BucketName
      LexFileKey: !Ref LexBotS3FileKey
      FulfillmentLambda: !Ref LambdaFunctionARN

Outputs:
  IAMRoleName:
    Description: Name of IAM Role used for Lex Custom Resource Operations
    Value: !Ref LexBotIAMRole
  
  IAMRoleARN:
    Description: ARN of IAM Role for used Lex Custom Resource Operations
    Value: !GetAtt LexBotIAMRole.Arn

  LambdaFunctionName:
    Description: Name of Lambda function used for Lex Custom Resource Operations
    Value: !Ref LexBotOpsFunctionTest
  
  LambdaFunctionARN:
    Description: ARN of Lambda Function used for Lex Custom Resource Operations
    Value: !GetAtt LexBotOpsFunctionTest.Arn


